apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: universal-reminders-evaluator
  labels:
    app: universal-reminders-evaluator
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: universal-reminders-evaluator
              image: <image-name>
              resources:
                limits:
                  memory: 1536Mi
                  cpu: 1
                requests:
                  memory: 1536Mi
                  cpu: 1
              env:
                - name: POSTGRES_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      key: postgres_connection_string
                      name: universal-reminders-secrets
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      key: slack_webhook_url
                      name: universal-reminders-secrets
              args:
                - python
                - reminder_evaluator.py
          restartPolicy: Never
